<?php
/**
 * @file
 * Main file for the Metatag Replace module.
 */

/**
 * Implements hook_permission().
 */
function comment_search_replace_permission() {
  return array(
    'comment_search_own' => array(
      'title' => t('Search own Comment'),
      'description' => t('Allow people to search own comments'),
    ),
      'comment_search_any' => array(
      'title' => t('Search any Comment'),
      'description' => t('Allow people to search any comments'),
    ),
    'comment_replace_own' => array(
      'title' => t('Replace own Comment'),
      'description' => t('Allow people to Replace own comments'),
    ),
   
    'comment_replace_any' => array(
      'title' => t('Replace any Comment'),
      'description' => t('Allow people to Replace own comments'),
    ),
  );
}

/**
 * Implements hook_help().
 */
function comment_search_replace_help($path, $arg) {
  switch ($path) {
    case "admin/help#metatag_replace":
      $text = t("<h1>Metatag Replace</h1><p>Metatag Replace is used to either search or replace Meta tags on your site.");
      return $text;
  }
}

/**
 * Implements hook_menu().
 */
function comment_search_replace_menu() {
  $items['admin/content/comment/search'] = array(
    'title callback' => 'Comment Search Replace',
    'title' => 'Comment Search Replace',
    'description' => 'Comment Search Replace',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('comment_search_replace_form'),
    'access arguments' => array(1),
    'access callback'=>'comment_search_replace_role',
    'file' => 'comment_search_replace_admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

//  $items['admin/content/comment/confirm'] = array(
//    'title' => 'Confirm Replace',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('metatag_replace_confirm_form'),
//    'access arguments' => array('metatag_replace_confirm'),
//    'file' => 'metatag_replace_admin.inc',
//    'type' => MENU_CALLBACK,
//  );
  return $items;
}
function comment_search_replace_role()
{
  return user_access('comment_search_any') || user_access('comment_search_own') || user_access('comment_replace_own') || user_access('comment_replace_any');
}
?>