<?php
function alternate_h2_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $form['alternate_site_h2_text'] = array(
      '#type' => 'textfield',
      '#title' => t('Multiple H2'),
      '#default_value' => variable_get('alternate_site_h2_text', ''),
      '#maxlength' => 128, 
      '#collapsible' => TRUE, 
      '#collapsed' => TRUE, 
      '#description' => t('Sets site-wide &#60h2&#62;  &#60;?php print $site_h2 ?&#62;'),
    );
    $form['alternate_site_h2_nid'] = array(
      '#type' => 'textarea',
      '#title' => t('Nid for nodes Having different H2'),
      '#default_value' => variable_get('alternate_site_h2_nid', ''),
      '#maxlength' => 225, 
      '#collapsible' => TRUE, 
      '#collapsed' => TRUE, 
      '#description' => t('Enter comma seperated nid of node ex 23,45,56'),
    );
  }
}
/**
 * Implementation of hook_permission().
 */
function alternate_h2_permission() {
  return array(
    'alternate_h2' => array(
      'title' => t('alternate_h2'),
      'description' => t('to Add alternate h2 '),
    ),
  );
}
/**
 * Implementation of hook_help().
 */
function alternate_h2_help($path, $arg) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#h2":
      $output = '<p>'.  t('Enter alternate H2 tags and comma seperated nid of pages on which it will show') .'</p>';
      break;
  }
  return $output;
} 
function alternate_h2_preprocess()
{
      $variables['alternate_site_h2_text'] = '<h2>' . variable_get('alternate_site_h2_text', '') . '</h2>';

}

