<?php
/**
 * @file
 * Main file for the Metatag Import Export module.
 */

/**
 * Implements hook_permission().
 */
function metatag_import_export_permission() {
  return array(
    'metatag_import' => array(
      'title' => t('Metatag Import'),
      'description' => t('Allow people to Import metatag from a CSV file'),
    ),
    'metatag_export' => array(
      'title' => t('Metatag Export'),
      'description' => t('Allow people to Export metatag to a CSV file'),
    ),
  );
}
/**
 * Implements hook_help().
 */
function metatag_import_export_help($path, $arg) {
  switch ($path) {
    case "admin/help#metatag_import_export":
      $text = t("<h3>Upload Metatags in bulk from a CSV file.</h3> 
          It Uses Batch API to Read Meta tags from the CSV file and updates the 
          metatag for the nodes specified for the path wriiten in first column. 
   Module supports 4 fields which are provided by <a href='https://www.drupal.org/project/metatag'>Metatag module</a> . 
   A sample CSV files is located inside sample folder. For more Information Please visit the project page
   <a href='https://www.drupal.org/node/2738695'>https://www.drupal.org/node/2738695</a></p>");
      return $text;
  }
}

/**
 * Implements hook_menu().
 */
function metatag_import_export_menu() {
  $items['admin/config/search/metatags/import'] = array(
    'title' => 'MetaTag Import',
    'description' => 'Import Metatag from a csv file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_import_export_upload_form'),
    'access arguments' => array('metatag_import'),
    'file' => 'metatag_import_export_upload_admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/config/search/metatags/export'] = array(
    'title' => 'MetaTag Export',
    'description' => 'Export Metatag to a csv file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_import_export_download_form'),
    'access arguments' => array('metatag_export'),
    'file' => 'metatag_import_export_download_admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
