<?php
/**
 * @file
 * Main file for the Metatag Import Export module.
 */

/**
 * Implements hook_permission().
 */
function metatag_import_export_csv_permission() {
  return array(
    'metatag_import_csv' => array(
      'title' => t('Metatag Import'),
      'description' => t('Allow people to Import metatag from a CSV file'),
    ),
    'metatag_export_csv' => array(
      'title' => t('Metatag Export'),
      'description' => t('Allow people to Export metatag to a CSV file'),
    ),
  );
}
/**
 * Implements hook_help().
 */
function metatag_import_export_csv_help($path, $arg) {
  switch ($path) {
    case "admin/help#metatag_import_export_csv":
      $text = t("<h3>Import or Export Metags with the help of a csv file.</h3> 
     <h4>Metatag Import</h4>
<p> Import Metatags from a CSV file. For the CSV format a Sample file is included inside sample folder.</p>
<h4> Metatag Export</p>
<p> Export Metatags bsed on content type to a CSV file </p>
<p> Module supports 4 fields which are provided by <a href='https://www.drupal.org/project/metatag'>Metatag module</a> . 
  For more Information Please visit the project page
  <a href='https://www.drupal.org/node/2738695'>https://www.drupal.org/node/2738695</a></p>");
      return $text;
  }
}

/**
 * Implements hook_menu().
 */
function metatag_import_export_csv_menu() {
  $items['admin/config/search/metatags/import'] = array(
    'title' => 'MetaTag Import',
    'description' => 'Import Metatag from a csv file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_import_export_csv_upload_form'),
    'access arguments' => array('metatag_import_csv'),
    'file' => 'metatag_import_export_csv_upload_admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/config/search/metatags/export'] = array(
    'title' => 'MetaTag Export',
    'description' => 'Export Metatag to a csv file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_import_export_csv_download_form'),
    'access arguments' => array('metatag_export_csv'),
    'file' => 'metatag_import_export_csv_download_admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
