<?php
/**
 * @file
 * Main file for the Metatag Bulk Uploader module.
 */

/**
 * Implements hook_permission().
 */
function metatag_bulk_uploader_permission() {
  return array(
    'metatag_bulk_uploader' => array(
      'title' => t('Metatag Bulk Uploader'),
      'description' => t('Allow people to upload metatag in bulk'),
    ),
  );
}
/**
 * Implements hook_help().
 */
function metatag_bulk_uploader_help($path, $arg) {
  switch ($path) {
    case "admin/help#metatag_bulk_uploader":
      $text = t("<h3>Upload Metatags in bulk from a CSV file.</h3> 
          It Uses Batch API to Read Meta tags from the CSV file and updates the metatag for the nodes specified for the path specified
   Module supports 4 fields which are provided by <a href='https://www.drupal.org/project/metatag'>Metatag module</a> . 
   A sample CSV files is located inside sample folder. For more Information Please visit the project page
   <a href='https://www.drupal.org/node/2738695'>https://www.drupal.org/node/2738695</a></p>");
      return $text;
  }
}

/**
 * Implements hook_menu().
 */
function metatag_bulk_uploader_menu() {
  $items['admin/config/search/metatags/bulk_update'] = array(
    'title' => 'MetaTag Bulk Uploader',
    'description' => 'Upload Metatag in bulk from a csv file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_bulk_uploader_form'),
    'access arguments' => array('metatag_bulk_uploader'),
    'file' => 'metatag_bulk_uploader_admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}