<?php


function node_creator_permission() {
  return array(
    'node_creator' => array(
      'title' => t('Node Creator'),
      'description' => t('Allows to create node'),
    ),
  );
}


function node_creator_menu() {
  $items['admin/config/system/node-creator'] = array(
    'title callback' => 'Create Node',
    'title' => 'Node creator',
    'description' => 'create nodes form a page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_creator_form'),
    'access arguments' => array('node_creator'),
    'file' => 'includes/node_creator.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}