<?php
/**
 * @file
 * Main file for the Metatag Replace module.
 */

/**
 * Implements hook_permission().
 */
function comment_search_replace_permission() {
  return array(
    'comment_search' => array(
      'title' => t('Coomment Search'),
      'description' => t('Allow people to search comments with Comment Search  Replace'),
    ),
    'comment_replace' => array(
      'title' => t('Comment Replace'),
      'description' => t('Allow people to Replace comments with Comment Search Replace'),
    ),
  );
}

/**
 * Implements hook_help().
 */
function comment_search_replace_help($path, $arg) {
  switch ($path) {
    case "admin/help#metatag_replace":
      $text = t("<h1>Metatag Replace</h1><p>Metatag Replace is used to either search or replace Meta tags on your site.");
      return $text;
  }
}

/**
 * Implements hook_menu().
 */
function comment_search_replace_menu() {
  $items['admin/content/comment/search'] = array(
    'title callback' => 'Comment Search Replace',
    'title' => 'Comment Search Replace',
    'description' => 'Comment Search Replace',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('comment_search_replace_form'),
    'access arguments' => array('comment_search'),
    'file' => 'comment_search_replace_admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

//  $items['admin/content/comment/confirm'] = array(
//    'title' => 'Confirm Replace',
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('metatag_replace_confirm_form'),
//    'access arguments' => array('metatag_replace_confirm'),
//    'file' => 'metatag_replace_admin.inc',
//    'type' => MENU_CALLBACK,
//  );
  return $items;
}
?>