<?php
/**
 * @file
 * Main file for the Metatag Replace module.
 */

/**
 * Implements hook_permission().
 */
function metatag_bulk_uploader_permission() {
  return array(
    'metatag_bulk_uploader' => array(
      'title' => t('Metatag Bulk Upload'),
      'description' => t('Allow people to search with Metatag Replace'),
    ),
  );
}
/**
 * Implements hook_help().
 */
function metatag_bulk_uploader_help($path, $arg) {
  switch ($path) {
    case "admin/help#metatag_replace":
      $text = t("Upload Metatag in bulk with the help of a C.S.V");
      return $text;
  }
}

/**
 * Implements hook_menu().
 */
function metatag_bulk_uploader_menu() {
  $items['admin/config/search/metatags/bulk_update'] = array(
    'title' => 'MetaTag Bulk update',
    'description' => 'Upload Metatag in bulk with the help of a C.S.V',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_bulk_uploader_form'),
    'access arguments' => array('metatag_bulk_uploader'),
    'file' => 'metatag_bulk_uploader_admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}